### ISSUE TITLE
clothes bug

### ISSUE THREAD

**Issue by berengma** [DokimiCU/Exile#17]
put a hat in your clothes inventory.
keep it there.
take an other hat and click with it on the one in the inventory.
You can adjust the temperature tolerance to any value you like, just by keep clicking.
This works also with the other clothes.

**Comment by DokimiCU** [comment]
fixed

**Comment by jeremyshannon** [comment]
I'm afraid this bug is still present. I was swapping out my lighter clothes for winter gear (having just come back to the surface) and my resist values started going up instead of down. I then took everything off and this was the result:
![screenshot_20201101_000819](https://user-images.githubusercontent.com/23157047/97810102-46608e00-1c26-11eb-972a-de55530de0f5.png)
